### PR TITLE
Boring packaging stuff

### PR DESCRIPTION
**Pull request by aawdls**
Implement recommended pattern in __init__.py
    Add __all__ definitions to each module. Import each module in
    __init__.py and define a top-level __all__.
    Move other defs from __init__.py into utils to avoid circular
    imports, but keep them in global __all__ to not break exisitng
    uses.

Change all imports to relative

### CODE REVIEW

**Comment by aawdls** [comment]
Hmm it looks like new the __all__ definitions aren't showing up as covered. I'll probably need to add some tests that do some `import *`s.

**Comment by aawdls** [comment]
I'm going to ignore the remaining codecov error because it is for lines that I have not changed, only moved.

**Comment by willrogers** [comment]
What was it that codecov was complaining about exactly? I am not at all a fan of checks that you end up ignoring.

**Comment by aawdls** [comment]
One particular function that was moved between files, in its "patch" check. It counts it as an added line that is not covered.
https://github.com/dls-controls/aapy/runs/2932408306

I didn't think I could write a non-trivial test for it.

**Comment by willrogers** [comment]
In which case, is it a reasonable check to be applying? I don't think we want to be aiming for 100% code coverage.

**Comment by aawdls** [comment]
Not really. I'll see if I can turn that part off or at least make it not mark the check as failed.

**Pull request merged**
