### PR TITLE
Add aa.rest.AaRestClient.resume_archiging_pv

### PR DESCRIPTION
**Pull request by aawdls**

### CODE REVIEW

**Comment by aawdls** [comment]
The linting checks have failed but seemingly not because of my changes

**Comment by willrogers** [comment]
It appears that pylint added a rule `raise-missing-from` in 2.6.0 that is now failing. You could fix this in `fetcher.py` line 67 by adding `as e` to the exception and `from e` at the end of the offending line. I think.

**Comment by willrogers** [comment]
The changes look pretty trivial so as long as they work I'm happy.

**Comment by aawdls** [comment]
Yes I have tested it and seems to work OK.

**Comment by aawdls** [comment]
Linter now happy. There is a problem with dependencies on python 2.7. I don't feel like looking into that right now.

**Comment by willrogers** [comment]
I gave you dud advice. That 'fix' does break Python 2 and it was hidden by the dependency problem. At least I went back and checked.

I hope the branch I have force-pushed will pass.

**Pull request merged**
